webapp:
  build: .
  volumes:
    - ../:/apps/crud
  working_dir: /apps/crud
  ports:
    - 82:80
  links:
    - mysql
  environment:
    MYSQL_DATABASE: crud
    MYSQL_USER: crud
    MYSQL_PASSWORD: crud@123456

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: crud
    MYSQL_USER: crud
    MYSQL_PASSWORD: crud@123456
  volumes:
    - ./mysqldata:/var/lib/mysql
  ports:
    - 33062:3306

redis:
  image: redis:latest
  ports:
    - 6380:6379
